[package]
name = "derintolu/small-business-truth-site"
version = "0.1.0"
description = "The Small Business Truth - exposing tax inequity"

[dependencies]
"sharrattj/static-web-server" = "1"

[fs]
"/public" = "dist"
